# Generated by Django 4.2 on 2023-04-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(max_length=30)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animalscategory')),
                ('volunteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteers')),
            ],
        ),
    ]
