# Generated by Django 4.2 on 2023-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
