# Generated by Django 4.2 on 2023-04-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='volunteers',
        ),
    ]
